### ISSUE TITLE
Fixing Audio clarification

### ISSUE THREAD

**Issue by panas78** [dortania/OpenCore-Desktop-Guide#13]
In fixing audio guide clarification missing about swapping bytes when defining 'alc-layout-id'.
https://dortania.github.io/OpenCore-Desktop-Guide/post-install/audio.html

**Comment by khronokernel** [comment]
Thanks, fixed in latest commit: 8722f4c
Regarding the swapping itself, AppleALC maxes out at layout-id 188 so would never pass the threshold of 255/FF
Edit: Eh why not, saves me an edit in 15 years when we hit that many layouts ;p
Fixed here as well: 046dfd3
