### ISSUE TITLE
Fixing iServices. 

### ISSUE THREAD

**Issue by panas78** [dortania/OpenCore-Desktop-Guide#14]
Hello,
While reading your beautiful guide, that so far helped me setup a near perfect build ,i stumbled upon the suggestion of using a serial number that belongs to an actual Mac that is not yet registered.
Purchase Date not Validated
I think that's going to produce some awkward situation when that serial will be actually purchased.

https://dortania.github.io/OpenCore-Desktop-Guide/post-install/iservices.html#generate-a-new-serial

**Comment by khronokernel** [comment]
Added a note: df34fb8
