### ISSUE TITLE
Fixing iServices ROM results in parse error

### ISSUE THREAD

**Issue by willco007** [dortania/OpenCore-Desktop-Guide#16]
In the iServices section, it lists entering your 12 digit MAC address into the ROM field as data. However, OpenCore logs that it is an invalid value upon booting with a 12 digit value. It seems like it wants an 8 digit number. Could the docs be updated to reflect this, thanks.

**Comment by khronokernel** [comment]
> plist data, 6 bytes

12 digit value is what it expects, check the Configuration.pdf. If it throws an error in your logs, the it’s outside the this guide and should be discussed on the Acidanthera bug tracker
