### ISSUE TITLE
iasl FixShutdown-USB-SSDT.dsl: Error 6004 - Too many arguments

### ISSUE THREAD

**Issue by kommtzeitkonrad** [dortania/OpenCore-Desktop-Guide#17]
Compiling `FixShutdown-USB-SSDT.dsl` with latest `iasl` results in Error 6004.
 
```
% iasl FixShutdown-USB-SSDT.dsl 

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200326
Copyright (c) 2000 - 2020 Intel Corporation

FixShutdown-USB-SSDT.dsl     16:         ZPTS (Arg0)
Error    6004 -         Too many arguments ^  (according to previous use, ZPTS requires 0)

ASL Input:     FixShutdown-USB-SSDT.dsl -     677 bytes      4 keywords     24 source lines

Compilation failed. 1 Errors, 0 Warnings, 0 Remarks
No AML files were generated due to compiler error(s)
```

**Comment by khronokernel** [comment]
What version of iASL? I just tested it with maciASL and compiled just fine

**Comment by khronokernel** [comment]
Realized it says in the logs, where did you get this from?

**Comment by kommtzeitkonrad** [comment]
Compiled it according to [the instructions at acidanthera/MaciASL/README.md](https://github.com/acidanthera/MaciASL/blob/master/README.md#compiling-iasl) with the latest code from https://github.com/acpica/acpica/.

**Comment by khronokernel** [comment]
```
C:\Users\Mykola Grymalyuk>"C:\Users\Mykola Grymalyuk\Downloads\iasl-win-20200326\iasl.exe" "C:\Users\Mykola Grymalyuk\Downloads\OpenCore-Desktop-Guide-master\OpenCore-Desktop-Guide-master\extra-files\FixShutdown-USB-SSDT.dsl"

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200326
Copyright (c) 2000 - 2020 Intel Corporation

ASL Input:     C:/Users/Mykola Grymalyuk/Downloads/OpenCore-Desktop-Guide-master/OpenCore-Desktop-Guide-master/extra-files/FixShutdown-USB-SSDT.dsl -     677 bytes      4 keywords     24 source lines
AML Output:    C:/Users/Mykola Grymalyuk/Downloads/OpenCore-Desktop-Guide-master/OpenCore-Desktop-Guide-master/extra-files/FixShutdown-USB-SSDT.aml -     108 bytes      3 opcodes       1 named objects

Compilation successful. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
```

No issue on my end, though I grabbed the prebuilt from [acpica](https://www.acpica.org/downloads/binary-tools) so it may just be an issue with the source. Once there's a new [release](https://github.com/acpica/acpica/releases) you can message back but atm I see no issue with the SSDT itself

**Comment by dhinakg** [comment]
@kommtzeitkonrad Can you upload your local copy please?

**Comment by kommtzeitkonrad** [comment]
As @khronokernel guessed correctly, it was an issue with the source that was fixed in https://github.com/acpica/acpica/commit/cde28e77356846f1f1d723b0a79259d53ebd3586.
> @kommtzeitkonrad Can you upload your local copy please?

In case you are still interested:

not working: [iasl-36cf9e1.zip](https://github.com/dortania/OpenCore-Desktop-Guide/files/4526286/iasl-36cf9e1.zip)

working: [iasl-cde28e7.zip](https://github.com/dortania/OpenCore-Desktop-Guide/files/4526288/iasl-cde28e7.zip)
