### ISSUE TITLE
Device properties for Coffee Lake not very clear

### ISSUE THREAD

**Issue by ryudice** [dortania/OpenCore-Desktop-Guide#20]
Hi,
Thanks for the guide it is really is very useful. I'm not sure if this is the right place to add suggestions but I found the coffee lake device properties part very confusing. It refers you to the whatevergreen guide which is even more confusing. The guide doesnt give examples of the values you should use, I know this depends on the GPU you are using but it doesn't say if this is needed even.

Overall the guide is great, thanks for investing your time helping others.

**Comment by khronokernel** [comment]
> The guide doesnt give examples of the values you should use

What do you mean? It tells you about main vs headless platform IDs and tells you about the stolenmem patch, what else is there to say about desktops?:

platform-id:
```
* `0x3E9B0007` - this is used when the Desktop iGPU is used to drive a display
  * `07009B3E` when hex-swapped
* `0x3E920003` - this is used when the Desktop iGPU is only used for computing tasks and doesn't drive a display
  * `0300923E` when hex-swapped
```
stolenmem:
```
We also add 2 more properties, `framebuffer-patch-enable` and `framebuffer-stolenmem`. The first enables patching via WhateverGreen.kext, and the second sets the min stolen memory to 19MB. This is usually unnecessary, as this can be configured in BIOS(64MB recommended) but required when not available.
```

It even provides an example table:

```
| Key | Type | Value |
| :--- | :--- | :--- |
| AAPL,ig-platform-id | Data | 07009B3E |
| framebuffer-patch-enable | Data | 01000000 |
| framebuffer-stolenmem | Data | 00003001 |

(This is an example for a desktop UHD 630 without a dGPU and no BIOS options for iGPU memory)
```

If you could elaborate more on what you're looking for, it would be much appreciated, as atm I'm a little confused and wondering if we're even looking at the same page: [Coffeelake DeviceProperties](https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/coffee-lake.html#deviceproperties)

**Comment by khronokernel** [comment]
Closing this issue as I see nothing to fix, you can comment if there are issues but please be specific next time
