### ISSUE TITLE
Missing framebuffer-fbmem from DVMT 32mb examples

### ISSUE THREAD

**Issue by 1Revenger1** [dortania/OpenCore-Desktop-Guide#26]
Let Whatevergreen docs
![Screenshot_20200429-023708](https://user-images.githubusercontent.com/13190749/80581826-98e49780-89c2-11ea-8363-f65d8d14a544.jpg)

Probably an issue in new laptop guide as well

**Comment by khronokernel** [comment]
Fixed in desktop guide, laptop guide actually has it correct so doesn't need any edits
