### ISSUE TITLE
apfs_keybag_init:1583: failed to initialize volume keybag, err = 2

### ISSUE THREAD

**Issue by qqsir-dev** [dortania/OpenCore-Desktop-Guide#27]
Could you help to figure out what is related for showing "apfs_keybag_init:1583: failed to initialize volume keybag, err = 2" message? its not stuck, but always can see it :(
Thanks

**Comment by khronokernel** [comment]
Please keep troubleshooting to forums, the issues tab is not a personal help centre. This should only be used if there are issues with the guide itself.

Tip: Turn verbose on a real Mac, there's gonna be a shit ton of errors as well. So there's no way to fix every error message in a hack

**Comment by qqsir-dev** [comment]
got it, Thank you.
