### ISSUE TITLE
Issue when creating the macOS USB installer

### ISSUE THREAD

**Issue by sumukshashidhar** [dortania/OpenCore-Desktop-Guide#28]
Platform: MacOS

Hello, 

I noticed this when creating the MacOS usb using GibmacOS. The newest version of GibmacOS outputs the files to a release folder, and does not supply an application for the next command to work. (flashing the usb)

For reference, here is a folder structure once gibmacOS has done its job.

![Screen_Shot_2020-04-29_at_10 02 18_AM](https://user-images.githubusercontent.com/46789005/80606314-cd536480-8a51-11ea-88ab-62b5aef2c909.png)

I saw multiple instances of this in the HackintoshParadise discord server as well.

Is this a known issue? Because it is possible to successfully follow the guide after downloading directly from the App Store.

**Comment by khronokernel** [comment]
Did you run the `BuildmacOSInstallApp.command`? This is what supplies you with the .app, by default gibMacOS only provides the installer in pieces

**Comment by sumukshashidhar** [comment]
strange, I redid it after you told me to and it worked. I'm 99% positive that I tried it the first time. But for now, it looks like my bad. I'll update you if I see this again.

Thanks!
