### ISSUE TITLE
Suggest trying all USB-ports

### ISSUE THREAD

**Issue by Roryvdb** [dortania/OpenCore-Desktop-Guide#30]
In the troubleshooting section about "Prohibited Sign error", there is an explanation about why macOS can't find the hardware/ports and how to fix this through mapping or by using certain kexts. However, it might be possible that only a few USB-ports do not work, and the boot-usb is plugged in one of these ports. So suggesting to try all USB-ports first, might offer an easy solution to get through the installer, as fixing the port mapping is easier during post-install, with the tools available on macOS.

**Comment by khronokernel** [comment]
Thanks for the issue, fixed in latest: https://github.com/dortania/OpenCore-Desktop-Guide/commit/1df9c33baf2de31c48092f0c768ce798459af99e
