### ISSUE TITLE
macOS booting issues: couldn't find my disk drives in Disk Utility

### ISSUE THREAD

**Issue by salehif** [dortania/OpenCore-Desktop-Guide#32]
Hi,

I had problem in my ASUS chipset z270 with intel 7700K "Desktop"

the problem was I can't find my HDD/SSD in Disk Utility at install or even after install macOS
FYI, NVMe SSD PCIe show only

to FIX this was turn OFF MY PC and turn ON same fixed the problem, if I do RESTART won't show my disk drives, so every time I won't to install/run macOS I need to turn OFF my PC completely to show HDD/SSD disk drives

hope to add this to macOS booting issues section

thank you

**Comment by khronokernel** [comment]
That's not really a "fix", sounds like a power state issue. If you're able to find a proper fix I'd be more than happy to add it but atm that sounds like it would either be something broken hardware wise or missing call in ACPI

**Comment by salehif** [comment]
@khronokernel to make the problem clear, this happen ONLY with macOS using OpenCore

with Windows 10 and Linux (i'm using fedora and ubuntu) the problem doesn't appear, I'm resrting my system often for updating etc... and never faced a problem like this on other OS.

I think it's linked more to OpenCore issue

Thank you
