### ISSUE TITLE
"EndRandomSeed" AND [EB|#LOG:EXITBS:START] ERROR issues

### ISSUE THREAD

**Issue by salehif** [dortania/OpenCore-Desktop-Guide#33]
Hi,

I had problem in my ASUS chipset z270 with intel 7700K "Desktop"

I faced two ERROR on BOOT with different versions of macOS

at 10.13.6 I faced this ERROR at BOOT
`"EndRandomSeed"`

and in 10.15.4 this ERROR at BOOT
`[EB|#LOG:EXITBS:START] ERROR`

to fix them was switching these two at config.plist file

`RebuildAppleMemoryMap` switch it NO

`SetupVirtualMap` switch it YES

I hope add this fix to the troubleshooting section, thank you

**Comment by shanghaidaddy** [comment]
I had similar issue with my ASUS Z170 Deluxe upgrade from 0.5.7, solved it with setting SetupVirtualMap to YES.

**Comment by khronokernel** [comment]
@salehif Are you sure RebuildAppleMemoryMap was part of the issue? It's shouldn't negatively impact desktops, but SetupVirtualMap can be a hit or miss depending on the vendor and BIOS version

**Comment by sataset** [comment]
Same issue here and the same solution ( `SetupVirtualMap` to `True`).

MSI B250i, CFG-Lock disabled in BIOS.

**Comment by salehif** [comment]
@khronokernel I'm sure, and for confirmation I tried again to make sure and clear
`RebuildAppleMemoryMap` to `True` and macOS won't bootup until put it back `False`

so for my motherboard ASUS ROG MAXIMUS XI CODE z270 with Intel 7700K

the system need to switch these two options as mentioned in issue

`RebuildAppleMemoryMap` to `False`
`SetupVirtualMap` to `True`

**Comment by khronokernel** [comment]
Sorry for the delay, thought I added it but apparently forgot until now: https://github.com/dortania/OpenCore-Desktop-Guide/commit/3c598c794065e751bb39a637e0ae61a7c147a429#diff-fc8d5cab3b1d5baa4ac280843a63db67
