### ISSUE TITLE
"post-install" invalid path

### ISSUE THREAD

**Issue by sataset** [dortania/OpenCore-Desktop-Guide#36]
Invalid path on this webpage:
- https://dortania.github.io/OpenCore-Desktop-Guide/post-install/
- https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#stuck-on-eblogexitbsstart

Invalid path: `post-install/msr-lock.md`
Valid path: `extras/msr-lock.md`

**Comment by khronokernel** [comment]
Gitbook fell back on the old path when the new one was invalid, even though the old path was also invalid. Issue was I forgot a `/`
Fixed in latest : https://github.com/dortania/OpenCore-Desktop-Guide/commit/0101656e0bc39e3b601cada398b149bca6410619
