### ISSUE TITLE
framebuffer-patch-enable	

### ISSUE THREAD

**Issue by panas78** [dortania/OpenCore-Desktop-Guide#40]
framebuffer-patch-enable and framebuffer-stolenmem
are not necessary when using a headless Platform id like 0x3E920003 

https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/coffee-lake.html#deviceproperties

**Comment by khronokernel** [comment]
Odd, thought I included a note but for some reason I didn't. Should be fixed now: 428847c
