### ISSUE TITLE
Installer Language Guide appears to be wrong

### ISSUE THREAD

**Issue by duncanhoggan** [dortania/OpenCore-Desktop-Guide#41]
The setting suggested for setting the language sets the language as hex but it looks like it should be base 64 encoded.

https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#macos-installer-in-russian

so...

en-US:0 -> IGVuLVVTOjA=
as the default
ru-RU:252 -> 72752d52553a323532

**Comment by dhinakg** [comment]
When using OpenCore string works fine

**Comment by duncanhoggan** [comment]
@dhinakg Was using a text editor, good to note a potential caveat, thanks.

**Comment by khronokernel** [comment]
Should be clarified: abdbf76
