### ISSUE TITLE
iGPU Haswell / intel HD4600 4K Config

### ISSUE THREAD

**Issue by nunsie** [dortania/OpenCore-Desktop-Guide#43]
Hi there,

Firstly, thank you for the amazing guide! I was able to setup my hackintosh with OpenCore successfully in just under 2 hours.

I would like to find out if it would be possible to include instructions on how to enable 4K for the HD4600 iGPU.

Basically I refer to this post:
https://www.insanelymac.com/forum/topic/330094-i7-4790s-integrated-intel-hd-4600-with-4k-monitor-samsung-ue510/

I am in the same boat here, windows and linux both boot into 4K so i know it isn't a hardware issue.

I understand, from the docs here: https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/haswell.html#deviceproperties
that properties such as the framebuffer mem and stolen mem can be set in the config.plist file - however I have no clue as to how the values we're converted (in that example - from 13MB to the hex value: 00003001)

I would basically like to apply what is done in that insanely mac post to my config. I also think it will be a really cool instruction to include in the documentation for other iGPU users with 4K monitors.

**Comment by khronokernel** [comment]
Hello,

So with iGPU patches, the guide isn't really going to go into more than the team is comfortable talking about. So something like the HD 4600 + 4k display situation isn't something we're really planning on putting too much time into as we have other guides in the works, PRs are always though if you have a guide you'd like to contribute. 

Regarding were all these values and properties came from, they're all from [AppleLife](https://www.applelife.ru/threads/intel-hd-graphics-3000-4000-4400-4600-5000-5500-5600-520-530-630.1289648/) and the [official WhateverGreen manual](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)(and these sites have some info also originating  from [Pike.R.Alpha's site](https://pikeralpha.wordpress.com) )

So my recommendation is to read into these threads and try out the patches listed. That thread you linked mentions patching RAM allocation, framebuffer memory size and VRAM allocation﻿ so I'd look into these patches:

* framebuffer-stolenmem(RAM)
* framebuffer-fbmem(Framebuffer Memory)
* framebuffer-unifiedmem(VRAM)

**Comment by nunsie** [comment]
Thank you for the recommendations @khronokernel !

I've since managed to get my iGPU to output 4k, albeit only @ 30Hz (this seems to be a limitation of the HDMI port of my motherboard, you may get higher rates with a display port) but still glad as I don't need to buy a GPU just yet.

For anyone else wondering how to get your HD4600 to output 4k, I have detailed the config.plist settings below:

### `NVRAM > Add > 7C436110-AB2A-4BBB-A880-FE41995C9F82`

| Key       | Type   | Value                | Notes                      |
|-----------|--------|----------------------|----------------------------|
| boot-args | String | Add `-cdfon` to args | Enables Core Display Fixup |


### `Device Properties > Add > PciRoot(0x0)/Pci(0x2,0x0)`

| Key                      | Type | Value    | Notes                                          |
|--------------------------|------|----------|------------------------------------------------|
| `AAPL,ig-platform-id`      | Data | `0300220D` | Recommended platform-id for Haswell iGPU       |
| `device-id`                | Data | `12040000` | device-id for the HD4600                       |
| `framebuffer-patch-enable` | Data | `01000000` | Enables framebuffer patches                    |
| `framebuffer-unifiedmem`   | Data | `00000080` | Increases VRAM from default 1536MB to 2048MB   |
| `framebuffer-stolenmem`    | Data | `00000004` | Increases RAM from 32MB to 64MB                |
| `framebuffer-fbmem`        | Data | `00002002` | Increases framebuffer memory from 19MB to 34MB |

Note: How the above memory values are calculated is as follows:

I will be calculating the `framebuffer-fbmem` above for this example.
- Take MB value and convert to bytes (in binary)
  - 1 Megabyte = 1 048 576 bytes
  - So `34 * 1 048 576 = 35651584`
- Convert decimal value above to hexadecimal
  - Theres numerous docs on the internet on how to do this, so I wont repeat it here. https://www.rapidtables.com/convert/number/decimal-to-hex.html
  - After conversion, our hex value is: `2200000`, signed 2's compliment: `02200000`
- hex-swap the above, results in `00002002`
