### ISSUE TITLE
Add Intel Bluetooth Support to the Guide

### ISSUE THREAD

**Issue by lese123** [dortania/OpenCore-Desktop-Guide#47]
The new IntelBluetoothFirmware.ext adds Intel Bluetooth support to macOS. Download it from https://github.com/zxystd/IntelBluetoothFirmware and add it to your OpenCore configuration.

This driver works very well on my Hackintosh laptop. The device ID on my computer is 8087:0AAA. I tried it with bluetooth headphones and a bluetooth keyboard. Both work very well. I could pair and use them without any issues.

I did not see this driver being mentioned anywhere in the Guide. I would like to recommend that it be added to the Guide. A lot of laptops come with Intel bluetooth chips.

**Comment by khronokernel** [comment]
I've known about the kext for some time, my main concern adding it is stability. I've seem it fail for users quite often, and even some instances where it kernel panics. Maybe down the road we'll reconsider but it's the same reason I don't include SMCAMDProcessor in the guide besides post-install and troubleshooting.

And for intel bluetooth, I don't really see a good place for it, though it's already mentioned in our [Wireless Buyers Guide](https://dortania.github.io/Wireless-Buyers-Guide/)
