### ISSUE TITLE
UHD 630 framebuffer broke after 10.15.5 update

### ISSUE THREAD

**Issue by jerw84** [dortania/OpenCore-Desktop-Guide#53]
Hey, I just wanted to note that the UHD 630 framebuffer broke with 10.15.5 and thought it might be a good idea to update it in the guide.

**Comment by khronokernel** [comment]
Could you elaborate? Is it an issue with our platformID choices? Otherwise I have not heard of the entire framebuffer breaking for all UHD 630 users(ofc Z390 users always have their issues, but that's just a poor platform too start with), and unsure what you want changed in the guide

**Comment by telepati** [comment]
@khronokernel it is related with this issue;
https://github.com/acidanthera/bugtracker/issues/938

**Comment by jerw84** [comment]
Of course. Sorry. Multiple users have reported that changing the platform id from 07009B3E to 00009B3E was necessary after the 10.15.5 update as the screen would just be black. I believe this is limited to z370 and z390 chipsets and I can also confirm this on my own z370/9900k hackintosh.

**Comment by khronokernel** [comment]
> 07009B3E to 00009B3E was necessary after the 10.15.5 update as the screen would just be black

Ah ok, yeah. I can definitely add a note regarding platform ID selection for iGPU-only Coffeelake users in the config and busID patching pages

**Comment by jerw84** [comment]
Awesome. Thanks so much for your hard work. This issue might also affect comet lake users as well but I cannot confirm that since I only have coffee lake.

**Comment by khronokernel** [comment]
CometLake is known working on DisplayPort(Vandroiy tested it with his Z490 system), though. don't believe he's tested HDMI(though might have missed that)

**Comment by smokingguns** [comment]
I have tried my best to fix igpu but badly failed. 
Z390 Aorus Master i5-8400. I hope the fix come out soon.

**Comment by krwt** [comment]
> Could you elaborate? Is it an issue with our platformID choices? Otherwise I have not heard of the entire framebuffer breaking for all UHD 630 users(ofc Z390 users always have their issues, but that's just a poor platform too start with), and unsure what you want changed in the guide

Could you elaborate why z390 is a poor platform? I thought the iMac 19,1 is using z390+9900k which makes it more compatible?

**Comment by khronokernel** [comment]
Added some troubleshooting in master, if this is still an issue in the release of 10.15.6 I will change the default value.

> Could you elaborate why z390 is a poor platform? I thought the iMac 19,1 is using z390+9900k which makes it more compatible?

@krwt Well besides the obvious firmware issues plaguing it, the biggest reason I'd avoid it is Acidanthera support. Currently it's on the same tier as AMD CPU hardware, being none.
Z490's on tier 1 support next to Z370 so you'd just have to hope that patches for one apply to yours as well but note that it's more common for something to get overlooked on Z390
