### ISSUE TITLE
Typo after the end of the Windows install guide 

### ISSUE THREAD

**Issue by voducngh** [dortania/OpenCore-Desktop-Guide#7]
There's a type error at the end of this page https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/winblows-install.html
Now with all this done, head to **Creating the USB** to finish up your work

Should be
Now with all this done, head to **Setting up the EFI** to finish up your work

**Comment by khronokernel** [comment]
Oh thank you, just fixed: e87c199
