### ISSUE TITLE
Clover installed extensions cleanup

### ISSUE THREAD

**Issue by tomasdev** [dortania/OpenCore-Desktop-Guide#8]
`clover-conversion` does not include steps into cleaning extensions installed on S/L/E or L/E... This  may be an edge case but I believe the scripts from RehabMan on Clover "keeping your system up to date" install kexts locally.

`kextstat | grep -v com.apple` is useful into detecting these.

Would be nice to have instructions on this, since if Clover was using FakeSMC and OC is trying to use VirtualSMC, there will be panics while trying to boot.

**Comment by tomasdev** [comment]
These worked for me:

# Open Terminal​
# Run: `open /Library/Extensions`, this will open a Finder window with the kexts, those that aren't Apple's had a gray dot. Remove those and empty your trash bin.
# Back to Terminal: `sudo -s`
# `mount -uw /​`
# `touch /Library/Extensions /System/Library/Extensions​`
# `kextcache -i /​`
# Restart​

**Comment by 1Revenger1** [comment]
Better tool for detecting kexts in S/L/E would probably be `sudo kextcache -i /` as it'll yell at you about any kexts that *shouldn't* be there.
